(() => {
  "use strict";
  const DEFAULT_API="https://looplink-api.obserax.workers.dev",TOKEN_KEY="looplink.admin.token.v1",API_KEY="looplink.admin.api.v1",$=id=>document.getElementById(id);
  const els={apiUrl:$("apiUrl"),adminToken:$("adminToken"),connectBtn:$("connectBtn"),refreshBtn:$("refreshBtn"),cloudState:$("cloudState"),endpointCount:$("endpointCount"),onlineCount:$("onlineCount"),pendingCount:$("pendingCount"),linkCount:$("linkCount"),lastRefresh:$("lastRefresh"),endpointList:$("endpointList"),endpointEmpty:$("endpointEmpty"),deviceList:$("deviceList"),deviceEmpty:$("deviceEmpty"),source:$("sourceEndpoint"),target:$("targetEndpoint"),direction:$("direction"),createLinkBtn:$("createLinkBtn"),linkList:$("linkList"),toast:$("toast")};
  let endpoints=[],links=[],timer=null,toastTimer;
  const apiBase=()=> (sessionStorage.getItem(API_KEY)||els.apiUrl.value||DEFAULT_API).replace(/\/+$/,'');
  const token=()=>sessionStorage.getItem(TOKEN_KEY)||els.adminToken.value.trim();
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const ago=e=>{const s=Math.max(0,Math.round(Date.now()/1000-Number(e||0)));return s<60?`${s}s ago`:s<3600?`${Math.floor(s/60)}m ago`:s<86400?`${Math.floor(s/3600)}h ago`:`${Math.floor(s/86400)}d ago`};
  const modeLabel=m=>({transmit:"Loop Transmit",broadcast:"Loop Broadcast",listen:"Loop Listen",talk:"Talk",stop:"Stopped",idle:"Idle"})[m]||m||"Unknown";
  function toast(m){els.toast.textContent=m;els.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>els.toast.classList.remove('show'),2400)}
  async function api(path,o={}){if(!token())throw new Error('Enter the LoopLink admin token.');const r=await fetch(apiBase()+path,{method:o.method||'GET',cache:'no-store',headers:{'content-type':'application/json','accept':'application/json','authorization':`Bearer ${token()}`},body:o.body===undefined?undefined:JSON.stringify(o.body)});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={error:t}}if(!r.ok)throw new Error(d.error||`API ${r.status}`);return d}
  function optionText(e){return `${e.display_name||e.endpoint_id} • ${e.kind}${e.online?' • online':''}`}
  function renderSelectors(){const approved=endpoints.filter(e=>e.status==='approved');for(const el of [els.source,els.target]){const old=el.value;el.innerHTML='<option value="">Select endpoint…</option>'+approved.map(e=>`<option value="${esc(e.endpoint_id)}">${esc(optionText(e))}</option>`).join('');if(approved.some(e=>e.endpoint_id===old))el.value=old}}
  function renderEndpoints(){els.endpointCount.textContent=endpoints.length;els.onlineCount.textContent=endpoints.filter(e=>e.online).length;els.pendingCount.textContent=endpoints.filter(e=>e.status==='pending').length;els.endpointEmpty.style.display=endpoints.length?'none':'block';els.endpointList.innerHTML='';for(const e of endpoints){const c=document.createElement('article');c.className=`device ${e.online?'':'offline'}`;const caps=e.capabilities||{};c.innerHTML=`<div><h3>${esc(e.display_name||e.endpoint_id)}</h3><div class="meta"><span class="status"><i class="dot ${e.online?'online':''}"></i>${e.online?'Online':'Offline'}</span><span>${esc(e.kind)}</span><span class="status-${esc(e.status)}">${esc(e.status)}</span><span>Pulse ${caps.pulse?'✓':'—'}</span><span>Vibrate ${caps.vibrate?'✓':'—'}</span><span>Audio ${caps.audio?'✓':'—'}</span><span>Seen ${ago(e.last_seen)}</span></div><div class="idcode">${esc(e.endpoint_id)}</div></div><div class="pinbox"><span>ROUTES</span><code>${Number(e.incoming_count||0)} in / ${Number(e.outgoing_count||0)} out</code></div><div class="controls endpoint-actions"></div>`;const actions=c.querySelector('.endpoint-actions');if(e.status==='pending'){const a=document.createElement('button');a.className='primary';a.textContent='Approve';a.onclick=()=>endpointAction(e,'approve');const r=document.createElement('button');r.textContent='Reject';r.onclick=()=>endpointAction(e,'reject');actions.append(a,r)}else{actions.innerHTML=`<span class="badge">${esc(e.kind==='android'?'Native Android':'Web endpoint')}</span>`}els.endpointList.append(c)}renderSelectors()}
  async function endpointAction(e,action){try{await api(`/api/admin/endpoints/${encodeURIComponent(e.endpoint_id)}/${action}`,{method:'POST'});toast(`${e.display_name||e.endpoint_id} → ${action}`);await refresh()}catch(err){showError(err)}}
  function renderLinks(){els.linkCount.textContent=links.length;els.linkList.innerHTML=links.length?'':'<div class="empty">No routes yet.</div>';for(const l of links){const row=document.createElement('div');row.className='link-row';row.innerHTML=`<div><strong>${esc(l.source_name||l.source_endpoint_id)}</strong><span> → </span><strong>${esc(l.target_name||l.target_endpoint_id)}</strong><small>${esc(l.source_kind)} → ${esc(l.target_kind)} • Pulse ${Number(l.pulse_enabled)?'on':'off'}</small></div><button class="danger">Remove</button>`;row.querySelector('button').onclick=async()=>{try{await api(`/api/admin/links/${encodeURIComponent(l.link_id)}`,{method:'DELETE'});toast('Link removed');await refresh()}catch(e){showError(e)}};els.linkList.append(row)}}
  function renderDevices(items){els.deviceEmpty.style.display=items.length?'none':'block';els.deviceList.innerHTML='';for(const item of items){const el=document.createElement('article');el.className=`device ${item.online?'':'offline'}`;el.innerHTML=`<div><h3>${esc(item.display_name||item.device_model||'Android device')}</h3><div class="meta"><span class="status"><i class="dot ${item.online?'online':''}"></i>${item.online?'Online':'Offline'}</span><span>${esc(item.device_model||'')}</span><span>Android ${esc(item.android_version||'?')}</span><span>App ${esc(item.app_version||'?')}</span><span>${Number(item.pair_count||0)} paired</span><span>Seen ${ago(item.last_seen)}</span></div><div class="idcode">${esc(item.device_id)}</div></div><div class="pinbox"><span>PERMANENT PIN</span><code>${esc(item.pairing_pin)}</code><div class="mode-badges"><span class="badge">Current: ${esc(modeLabel(item.current_mode))}</span><span class="badge desired">Desired: ${esc(modeLabel(item.desired_mode))}</span></div></div><div class="controls"><div class="mode-row"><select class="mode-select"><option value="transmit">Loop Transmit</option><option value="broadcast">Loop Broadcast</option><option value="listen">Loop Listen</option><option value="talk">Talk</option><option value="stop">Stop</option></select><button class="apply-mode primary">Apply</button><button class="check-config">Refresh Config</button><button class="check-update">Check Update</button></div></div>`;const s=el.querySelector('.mode-select');s.value=['transmit','broadcast','listen','talk','stop'].includes(item.desired_mode)?item.desired_mode:'transmit';el.querySelector('.apply-mode').onclick=()=>command(item,'mode',{mode:s.value},`${modeLabel(s.value)}`);el.querySelector('.check-config').onclick=()=>command(item,'config-refresh',null,'runtime config refresh sent');el.querySelector('.check-update').onclick=()=>command(item,'update',null,'update check sent');els.deviceList.append(el)}}
  async function command(item,what,body,msg){try{await api(`/api/admin/devices/${encodeURIComponent(item.device_id)}/${what}`,{method:'POST',body});toast(`${item.display_name||'Device'} → ${msg}`);if(what==='mode')await refresh()}catch(e){showError(e)}}
  async function refresh(){const [e,l,d]=await Promise.all([api('/api/admin/endpoints'),api('/api/admin/links'),api('/api/admin/devices')]);endpoints=e.items||[];links=l.items||[];els.cloudState.className='pill ok';els.cloudState.textContent='Admin API connected';els.lastRefresh.textContent=`Updated ${new Date().toLocaleTimeString()}`;renderEndpoints();renderLinks();renderDevices(d.items||[])}
  async function connect(){const value=els.apiUrl.value.trim().replace(/\/+$/,'');if(!/^https:\/\//i.test(value)&&!/^http:\/\/(localhost|127\.0\.0\.1)/i.test(value))throw new Error('Use an HTTPS Worker URL.');const t=els.adminToken.value.trim();if(!t)throw new Error('Enter the admin token.');sessionStorage.setItem(API_KEY,value);sessionStorage.setItem(TOKEN_KEY,t);await refresh();clearInterval(timer);timer=setInterval(()=>{if(!document.hidden)refresh().catch(showError)},15000)}
  function showError(e){console.error(e);els.cloudState.className='pill bad';els.cloudState.textContent=e?.message||'Admin API error';toast(e?.message||String(e))}
  els.createLinkBtn.onclick=async()=>{const source=els.source.value,target=els.target.value;if(!source||!target)return toast('Choose both endpoints');if(source===target)return toast('Choose two different endpoints');try{await api('/api/admin/links',{method:'POST',body:{source_endpoint_id:source,target_endpoint_id:target,direction:els.direction.value}});toast(els.direction.value==='both'?'Bidirectional link created':'Link created');await refresh()}catch(e){showError(e)}};
  els.connectBtn.onclick=()=>connect().catch(showError);els.refreshBtn.onclick=()=>refresh().catch(showError);els.adminToken.onkeydown=e=>{if(e.key==='Enter')connect().catch(showError)};els.apiUrl.value=sessionStorage.getItem(API_KEY)||DEFAULT_API;els.adminToken.value=sessionStorage.getItem(TOKEN_KEY)||'';if(token())connect().catch(showError);
})();
